trigger:
  - master

pool:
  vmImage: ubuntu-latest

jobs:
  - job: AgentJob1
    displayName: 'Agente de trabajo 1'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: NuGetToolInstaller@0
        displayName: 'Usar NuGet'
        inputs:
          versionSpec: 4.4.1

      - task: NuGetCommand@2
        displayName: 'Restaurar NuGet'
        inputs:
          restoreSolution: '$(Parameters.solution)'

      - task: VSBuild@1
        displayName: 'Compilar solución'
        inputs:
          solution: '$(Parameters.solution)'
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'

      - task: VSTest@2
        displayName: 'Pruebas de ensamblado'
        inputs:
          testAssemblyVer2: |
            **\$(BuildConfiguration)\*Tests*.dll
            **\$(BuildConfiguration)\*.*Tests*.dll
            **\$(BuildConfiguration)\**\*Tests*.dll
            **\$(BuildConfiguration)\**\*.*Tests*.dll
            !**\obj\**
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
        enabled: false

      - task: CopyFiles@2
        displayName: 'Copiar archivos a: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishSymbols@2
        displayName: 'Publicar ruta de símbolos'
        inputs:
          SearchPattern: '**\bin\**\*.pdb'
          PublishSymbols: false
        continueOnError: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publicar artefacto'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
          ArtifactName: '$(Parameters.ArtifactName)'
        condition: succeededOrFailed()

  - job: AgentJob2
    displayName: 'Agente de trabajo 2'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: echo Este trabajo se está ejecutando en el Agente2

  - job: AgentJob3
    displayName: 'Agente de trabajo 3'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: echo Este trabajo se está ejecutando en el Agente3
